// Code generated by ogen, DO NOT EDIT.

package publicapi

// OperationName is the ogen operation name
type OperationName = string

const (
	ListAccountsOperation OperationName = "ListAccounts"
	PostAccountOperation  OperationName = "PostAccount"
)
