// Code generated by ogen, DO NOT EDIT.

package publicapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ListAccounts implements list-accounts operation.
//
// Retrieves a list of accounts based on search parameters.
//
// GET /{customerId}/accounts
func (UnimplementedHandler) ListAccounts(ctx context.Context, params ListAccountsParams) (r ListAccountsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostAccount implements postAccount operation.
//
// Creates a new account.
//
// POST /{customerId}/accounts
func (UnimplementedHandler) PostAccount(ctx context.Context, req *Account, params PostAccountParams) (r PostAccountRes, _ error) {
	return r, ht.ErrNotImplemented
}
