// Code generated by ogen, DO NOT EDIT.

package publicapi

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// ListAccounts implements list-accounts operation.
	//
	// Retrieves a list of accounts based on search parameters.
	//
	// GET /{customerId}/accounts
	ListAccounts(ctx context.Context, params ListAccountsParams) (ListAccountsRes, error)
	// PostAccount implements postAccount operation.
	//
	// Creates a new account.
	//
	// POST /{customerId}/accounts
	PostAccount(ctx context.Context, req *Account, params PostAccountParams) (PostAccountRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
