// Code generated by ogen, DO NOT EDIT.

package privateapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetAccount implements getAccount operation.
//
// Allows to retrieve a list of accounts based on search parameters.
//
// GET /accounts
func (UnimplementedHandler) GetAccount(ctx context.Context, params GetAccountParams) (r GetAccountRes, _ error) {
	return r, ht.ErrNotImplemented
}
