// Code generated by ogen, DO NOT EDIT.

package privateapi

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// ListAccounts implements listAccounts operation.
	//
	// Allows to retrieve a list of accounts based on search parameters.
	//
	// GET /accounts
	ListAccounts(ctx context.Context, params ListAccountsParams) (ListAccountsRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
