// Code generated by ogen, DO NOT EDIT.

package privateapi

import (
	"net/http"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetAccountParams is parameters of getAccount operation.
type GetAccountParams struct {
	Cvu                  OptString `json:",omitempty,omitzero"`
	CvuAlias             OptString `json:",omitempty,omitzero"`
	DinoPayAccountNumber OptString `json:",omitempty,omitzero"`
}

func unpackGetAccountParams(packed middleware.Parameters) (params GetAccountParams) {
	{
		key := middleware.ParameterKey{
			Name: "cvu",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Cvu = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "cvuAlias",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.CvuAlias = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "dinoPayAccountNumber",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.DinoPayAccountNumber = v.(OptString)
		}
	}
	return params
}

func decodeGetAccountParams(args [0]string, argsEscaped bool, r *http.Request) (params GetAccountParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: cvu.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "cvu",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCvuVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotCvuVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Cvu.SetTo(paramsDotCvuVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Cvu.Get(); ok {
					if err := func() error {
						if err := (validate.String{
							MinLength:     0,
							MinLengthSet:  false,
							MaxLength:     0,
							MaxLengthSet:  false,
							Email:         false,
							Hostname:      false,
							Regex:         regexMap["^\\d{22}$"],
							MinNumeric:    0,
							MinNumericSet: false,
							MaxNumeric:    0,
							MaxNumericSet: false,
						}).Validate(string(value)); err != nil {
							return errors.Wrap(err, "string")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "cvu",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: cvuAlias.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "cvuAlias",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCvuAliasVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotCvuAliasVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.CvuAlias.SetTo(paramsDotCvuAliasVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.CvuAlias.Get(); ok {
					if err := func() error {
						if err := (validate.String{
							MinLength:     0,
							MinLengthSet:  false,
							MaxLength:     0,
							MaxLengthSet:  false,
							Email:         false,
							Hostname:      false,
							Regex:         regexMap["^[\\w\\.-]{6,20}$"],
							MinNumeric:    0,
							MinNumericSet: false,
							MaxNumeric:    0,
							MaxNumericSet: false,
						}).Validate(string(value)); err != nil {
							return errors.Wrap(err, "string")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "cvuAlias",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: dinoPayAccountNumber.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "dinoPayAccountNumber",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotDinoPayAccountNumberVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotDinoPayAccountNumberVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.DinoPayAccountNumber.SetTo(paramsDotDinoPayAccountNumberVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "dinoPayAccountNumber",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
