openapi: "3.0.0"

info:
  title: "Accounts Private API"
  description: "API to list accounts"
  version: "1.0.0"

paths:
  /accounts:
    get:
      summary: "Allows to retrieve a list of accounts based on search parameters"
      operationId: "listAccounts"
      parameters:
        - in: query
          name: id
          schema:
            type: string
            format: uuid
        - name: customerId
          in: query
          description: "Customer Id"
          schema:
            type: string
            format: uuid
        - in: query
          name: cvu
          schema:
            type: string
            pattern: '^\d{22}$'
        - in: query
          name: cvuAlias
          schema:
            type: string
            pattern: '^[\w\.-]{6,20}$'
        - in: query
          name: dinoPayAccountNumber
          schema:
            type: string
        - name: limit
          in: query
          description: "Number of accounts to return (for pagination)."
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 200
            default: 50
        - name: offset
          in: query
          description: "Offset for pagination."
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0

      responses:
        "200":
          description: "At least one account was found matching the provided parameters"
          content:
            application/json:
              schema:
                type: array
                maxItems: 100
                items:
                  $ref: "account.yaml#/components/schemas/account"
        "404":
          description: "There is no account matching the provided parameters"
