openapi: "3.0.0"

info:
paths:
  /accounts:
    post:
      summary: "Creates a new account"
      operationId: "postAccount"
      parameters:
        - name: "X-Walletera-Correlation-Id"
          in: "header"
          description: "a UUID that allows to trace end-to-end transactions"
          required: false
          schema:
            type: string
            format: "uuid"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "schemas.yaml#/components/schemas/account"
      responses:
        "201":
          description: "Account successfully created"
          content:
            application/json:
              schema:
                $ref: "schemas.yaml#/components/schemas/account"
        "400":
          description: "The provided parameters are incorrect"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/apiError"
        "401":
          description: "Unauthorized"
        "409":
          description: "The payment already exist"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/apiError"
        "500":
          description: "Internal error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/apiError"

    get:
      summary: "Allows to retrieve an list of accounts based on search parameters"
      operationId: "getAccount"
      parameters:
        - in: query
          name: accountType
          schema:
            type: string
            enum:
              - cvu
              - dinopay
        - in: query
          name: cvuAccountDetails
          schema:
            $ref: "schemas.yaml#/components/schemas/cvuAccountDetails"
          style: deepObject
          explode: true
        - in: query
          name: dinopayAccountDetails
          schema:
            $ref: "schemas.yaml#/components/schemas/dinopayAccountDetails"
          style: deepObject
          explode: true
      responses:
        "200":
          description: "At least one account was found matching the provided parameters"
          content:
            application/json:
              schema:
                type: array
                maxItems: 100
                items:
                  $ref: "schemas.yaml#/components/schemas/account"
        "404":
          description: "There is no account matching the provided parameters"

components:
  schemas:
    apiError:
      type: "object"
      description: "Body of the error responses"
      properties:
        errorMessage:
          type: "string"
          description: "A message describing the error"
        errorCode:
          type: "string"
          format: "uuid"
          description: "A unique identifier for the specific error"
      required:
        - "errorMessage"
        - "errorCode"
