openapi: "3.0.0"

info:
paths:
components:

  schemas:
    account:
      type: "object"
      description: "A Bank or PSP account"
      properties:
        id:
          type: "string"
          format: "uuid"
          description: "Walletera account unique identifier"
        currency:
          type: "string"
          description: "Account currency"
        customerId:
          description: "Id of the customer (institution) that owns the account"
          type: string
          format: uuid
        customerName:
          description: "Name of the customer (institution) that owns the account"
          type: string
        customerAccountId:
          type: "string"
          description: "Identifier assigned to the account by the customer"
        accountType:
          type: string
          enum:
            - cvu
            - dinopay
        accountDetails:
          description: "Extra account details. The details depend on the accountType."
          type: object
          oneOf:
            - $ref: "#/components/schemas/cvuAccountDetails"
            - $ref: "#/components/schemas/dinopayAccountDetails"
      required:
        - "id"
        - "amount"
        - "currency"
        - "customerId"
        - "accountType"
        - "accountDetails"

    cvuAccountDetails:
      type: object
      properties:
        cuit:
          description: "Account owner national identification number"
          type: string
          pattern: '^\d{11}$'
        cvu:
          type: string
          pattern: '^\d{22}$'
        alias:
          type: string

    dinopayAccountDetails:
      type: object
      properties:
        accountHolder:
          type: "string"
          description: "Name of the owner of the account"
        accountNumber:
          type: "string"
          description: "Account number on DinoPay"
      required:
        - "accountHolder"
        - "accountNumber"

    paymentUpdate:
      type: "object"
      description: "Body of the PATH /withdrawal request"
      properties:
        paymentId:
          type: "string"
          format: "uuid"
          description: "Payment Id"
        externalId:
          type: "string"
          description: "Id assigned to the operation by an external payment provider"
        schemeId:
          type: "string"
          description: "Id assigned to the operation by the payment scheme"
        status:
          type: "string"
          $ref: "#/components/schemas/paymentStatus"
          description: "Payment status"
        statusReason:
          type: "string"
      required:
        - "paymentId"
        - "status"

    paymentStatus:
      type: string
      enum:
        - "pending"
        - "delivered"
        - "confirmed"
        - "rejected"
        - "failed"

    apiError:
      type: "object"
      description: "Body of the error responses"
      properties:
        errorMessage:
          type: "string"
          description: "A message describing the error"
        errorCode:
          type: "string"
          format: "uuid"
          description: "A unique identifier for the specific error"
      required:
        - "errorMessage"
        - "errorCode"
